#===common params===
raw_dir : "/home/ug1754/project/BulkRNA/v1.0/rawdata"
work_dir : "/home/ug1754/project/BulkRNA/v1.0"
image : "/home/ug1754/project/BulkRNA/v1.0/script/../image/BulkRNA.sif"
samples : "/home/ug1754/project/BulkRNA/v1.0/samples.txt"
contrasts : "/home/ug1754/project/BulkRNA/v1.0/contrasts.txt"

#===genome index===
genome_index :
  genome : "/home/ug1754/project/BulkRNA/v1.0/script/../ref/genome.fa" 
  gtf : "/home/ug1754/project/BulkRNA/v1.0/script/../ref/genes.gtf"
  thread : 2

#===qc params===
qc :
  thread : 2

#===filter params===
filter :
  thread : 2

#===alignment params===
alignment :
  strandness : "F"
  thread : 4
sam2bam : 
  thread : 4

#===quantification===
quanti :
  featuretype : "exon"
  attritype : "gene_id"
  ispairend : "TRUE"
  strandness : 0
  thread : 2
        
